version: "3.9"

services:
  connector:
    image: basecamp/connector
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      WEB_HTTP_PORT: 9191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 9192
      WEB_HTTP_MANAGEMENT_PATH: /api/v1/management
      WEB_HTTP_DATA_PORT: 9292
      WEB_HTTP_DATA_PATH: /api/v1/data
      WEB_HTTP_IDS_PORT: 9293
      WEB_HTTP_IDS_PATH: /api/v1/ids
      EDC_API_AUTH_KEY: password

      EDC_DATASOURCE_DEFAULT_NAME: default
      EDC_DATASOURCE_DEFAULT_URL=JDBC:
      EDC_DATASOURCE_DEFAULT_USER:
      EDC_DATASOURCE_DEFAULT_PASSWORD:

      EDC_DATASOURCE_DATAPLANEINSTANCE_NAME: dataplaneinstance
      EDC_DATASOURCE_DATAPLANEINSTANCE_URL:
      EDC_DATASOURCE_DATAPLANEINSTANCE_USER:
      EDC_DATASOURCE_DATAPLANEINSTANCE_PASSWORD:

      EDC_DATASOURCE_ASSET_NAME: asset
      EDC_DATASOURCE_ASSET_URL:
      EDC_DATASOURCE_ASSET_USER:
      EDC_DATASOURCE_ASSET_PASSWORD:

      EDC_DATASOURCE_CONTRACTDEFINITION_NAME: contractdefinition
      EDC_DATASOURCE_CONTRACTDEFINITION_URL:
      EDC_DATASOURCE_CONTRACTDEFINITION_USER:
      EDC_DATASOURCE_CONTRACTDEFINITION_PASSWORD:

      EDC_DATASOURCE_CONTRACTNEGOTIATION_NAME: contractnegotiation
      EDC_DATASOURCE_CONTRACTNEGOTIATION_URL:
      EDC_DATASOURCE_CONTRACTNEGOTIATION_USER:
      EDC_DATASOURCE_CONTRACTNEGOTIATION_PASSWORD:

      EDC_DATASOURCE_POLICY_NAME: policy
      EDC_DATASOURCE_POLICY_URL:
      EDC_DATASOURCE_POLICY_USER:
      EDC_DATASOURCE_POLICY_PASSWORD:

      EDC_DATASOURCE_TRANSFERPROCESS_NAME: transferprocess
      EDC_DATASOURCE_TRANSFERPROCESS_URL:
      EDC_DATASOURCE_TRANSFERPROCESS_USER:
      EDC_DATASOURCE_TRANSFERPROCESS_PASSWORD:

      EDC_CLEARINGHOUSE_LOG_URL:
      BROKER_CLIENT_EXTENSION_ENABLED: "true"
      EDC_BROKER_BASE_URL:

      EDC_OAUTH_CERTIFICATE_ALIAS:
      EDC_OAUTH_PRIVATE_KEY_ALIAS:
      EDC_OAUTH_CLIENT_ID:
      EDC_OAUTH_TOKEN_URL:
      EDC_OAUTH_PROVIDER_JWKS_URL:
      EDC_OAUTH_PROVIDER_AUDIENCE: idsc:IDS_CONNECTORS_ALL
    ports:
      - "9191:9191"
      - "9192:9192"
      - "9292:9292"
      - "9293:9293"
